import psycopg2

def salon():
    return psycopg2.connect(
        dbname="postgres",
        user="postgres",
        password="41muyassar59",
        host="localhost",
        port="5432"
    )

def create_tables():
    avto = salon()
    cursor = avto.cursor()

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS admin (
            id INT GENERATED BY DEFAULT AS IDENTITY,
            daromad INT NOT NULL)

        ''')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS klient (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        name TEXT NOT NULL UNIQUE,
        history INT,
        balance DEC(15, 2) NOT NULL,
        PRIMARY KEY(id))

    ''')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS omborxona(
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        narxi INTEGER NOT NULL )
    ''')
    # rangini qo'sh
    avto.commit()
    print("✅ Barcha jadvallar yaratildi!")
    avto.close()

def add_klient(name,history,balance):
    avto = salon()
    cursor = avto.cursor()

    try:
        cursor.execute('''INSERT INTO klient(name,history,balance)
        VALUES ( %s,%s,%s) ON CONFLICT name DO NOTHING''',(name,history,balance))

        if not name:
            print("❌ ismingiz klientlar ro'hatida yo'q! Klientlar ro'hatoga qo'shiling!")
        if not balance:
            print("❌ sizning balansingizda pul yo'q!")
    except Exception:
        print("❌ xatolik ro'y berdi! ")

    finally:
        avto.commit()
        print(f"✅ {name} jadvalga qo'shildi! ")
        avto.close()


def add_moshina(name,narxi):
    avto = salon()
    cursor = avto.cursor()
    try:
        cursor.execute('''INSERT INTO omborxona(name,narxi)
        VALUES ( %s,%s)''', (name,narxi))

        if not name:
            print("❌ nomsiz mashina omborga qo'shilib bo'lmaydi!")
        if not narxi:
            print("❌ mashinani tekinga sotib bo'lmaydi !!!")
    except Exception:
        print("❌ xatolik ro'y berdi! ")


    finally:
        avto.commit()
        print(f"✅ {name} jadvalga qo'shildi! ")
        avto.close()

def klientoch():
    avto = salon()
    cursor = avto.cursor()

    cursor.execute(''' SELECT * FROM klient''')
    klient = cursor.fetchall()
    for k in klient:
        print(f"{k[0]}. {k[1]}, yoshi: {k[2]}da , balansida {k[3]} so'm bor")
    avto.close()

def mashinchik():
    avto = salon()
    cursor = avto.cursor()

    cursor.execute(''' SELECT * FROM omborxona''')
    omborxona = cursor.fetchall()
    for o in omborxona:
        print(f"{o[0]}. {o[1]} nomli mashina, {o[2]} , narxi {o[3]} so'm ")
    avto.close()

def mashina_sot():
    avto = salon()
    cursor = avto.cursor()

    ism = input("Ismingizni kiriting: ").title()

    cursor.execute("SELECT id, balance FROM klient WHERE name = %s", (ism,))
    klient = cursor.fetchone()

    if not klient:
        print("❌ Siz klientlar ro‘yxatida yo‘qsiz! Avval ro‘yxatdan qo'shiling! ")
        avto.close()
        return

    klient_id, balance = klient

    cursor.execute("SELECT id, name, narxi FROM omborxona")
    mashinalar = cursor.fetchall()

    if not mashinalar:
        print("❌ Omborda mashina yo‘q!")
        avto.close()
        return

    print("\n Mavjud mashinalar:")
    for m in mashinalar:
        print(f"{m[0]}. {m[1]} - {m[2]} so‘m")

    mashina_id = int(input("\nSotib olmoqchi bo‘lgan mashinani ID sini kiriting: "))

    cursor.execute("SELECT name, narxi FROM omborxona WHERE id = %s", (mashina_id,))
    mashina = cursor.fetchone()

    if not mashina:
        print("❌ Bunday mashina mavjud emas!")
        avto.close()
        return

    mashina_nomi, narxi = mashina

    if balance < narxi:
        print(f"❌ Sizda yetarli mablag‘ yo‘q! Kerak: {narxi} so‘m, Sizda: {balance} so‘m")
        avto.close()
        return

    cursor.execute("UPDATE klient SET balance = balance - %s WHERE id = %s", (narxi, klient_id))
    cursor.execute("DELETE FROM omborxona WHERE id = %s", (mashina_id,))
    cursor.execute("UPDATE admin SET daromad=daromad + %s WHERE id = 1 ", (narxi,))
    avto.commit()

    print(f"✅ {ism}, siz {mashina_nomi} mashinasini sotib oldingiz!")
    avto.close()
def get_daromad():
    avto = salon()
    cursor = avto.cursor()

    cursor.execute(''' SELECT daromad FROM admin''')
    daromad = cursor.fetchone()

    if daromad==0:
        print("😔 Bugun hech qanday daromad bo'lmadi")
    if daromad==None:
        print("😔 Bugun hech qanday daromad bo'lmadi")
    else:
        print(f" ja'mi daromad {daromad} so'm ")
    avto.close()

if __name__ == '__main__':
    create_tables()


    while True:
        print(("\nMashina salonini boshqarmasi:"))
        print("0. Dasturni to'xtatish")
        print("1. Server")
        print("2. Klient")

        tanlov=int(input("Tanlov kiriting: "))

        if tanlov == 0:
            print("dastur to'xtatildi! ")
            break

        if tanlov==1:
            while True:
                print("\nServers")
                print("0. Orqaga qaytish")
                print("1. Omborga mashina qo'shish")
                print("2. Hamma klientlarni ko'rish")
                print("3. Mashina omborini ko'rish")
                print("4. Daromadni ko'rish")

                vibor=int(input("Tanlov kiriting: "))

                if vibor==0:
                    break
                if vibor==1:
                    name=input("Qo'shmoqchi bo'lgan mashinani nomini kiriting: ").lower()
                    narxi=int(input(f"{name}ni narxini kiriting: "))
                    add_moshina(name,narxi)
                if vibor==2:
                    klientoch()
                if vibor==3:
                    mashinchik()
                if vibor==4:
                    get_daromad()

        if tanlov==2:
            while True:
                print("\nKlient:")
                print("0. Orqaga qaytish")
                print("1. Klient qo'shish")
                print("2. Mashina sotib olish")
                print("3. Zalogga moshina olish")
                print("4. Rassrochkaga moshina olish")


                choice = input("Tanlovingizni kiriting: ")
                if choice=='0':
                    break

                if choice == '1':
                    try:
                        name= input("ismingiz: ").title()
                        history=int(input("necha yoshsiz: "))
                        if history<18:
                            print("\n1. O'zingiz uchun")
                            print("2. Ota-ona uchun")
                            print("3. Boshqa")
                            kim=int(input("mashinani kim uchun olmoqchisiz: "))
                            if kim==1:
                                print("❌ siz hali mashina olish uchun kichiksiz")
                                break
                            elif kim==2:
                                print(input("pulingiz yetarlimi?(ha/yo'q): "))
                                if 'ha':
                                    print("unda tanlovingizni davom etavering ☺️")
                                else:
                                    break
                            elif kim==3:
                                print("✅ davom etishga ruhsat berildi ")
                        else:

                            print("✅")
                            continue

                        balance=int(input("💵 balansingizni kirirting: "))

                        if balance==0:
                            print("💸 balansingizda pul yetarli emas!")
                            continue
                        add_klient(name,history,balance)
                    except ValueError:
                        print("noto'g'ri qiymat!")
                if choice=='2':
                    mashina_sot()
